# -*- coding: utf-8 -*-
"""Tarea1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TcaBZnohCyzmtxEBrMvZqi-R4ZKbu_ru
"""

#Nombre: Priscila Brito
#Tarea1

#Creando la funcion para evaluar el estado de la bomba

def evaluar_estado(presion, temperatura):
    if presion > 3000 and temperatura > 150:
      return "Crítico"
    elif presion > 2500 or temperatura > 120:
      return "Precaución"
    else:
      return "Normal"

#Importar archivo CSV

import csv
with open ('/content/sensor_tarea.csv', mode='r') as archivo:

#Convirtiendo cada fila en diccionario Phyton
     lineas = csv.DictReader(archivo)

#Creando Diccionario e Iniciando conteo
     conteo = {"Crítico": 0, "Precaución": 0, "Normal": 0}

#Creando Listas Vacías
     presiones_anonalias = []
     temperaturas_anomalias = []

     for linea in lineas:
          p = float(linea['presion'])
          t = float(linea['temperatura'])
          print(f"presion: {p} | temperatura: {t}")

#Evaluando estado y actualizando conteo

          estado = evaluar_estado (p,t)
          conteo[estado] +=1

#Detectando si el estado es Crítico o Precaución
          if estado != 'Normal':
              presiones_anonalias.append(p)
              temperaturas_anomalias.append(t)

#Calculando las anamolias y el porcentaje de las anomalias

totaldedatos = sum(conteo.values())
totalanomalias = conteo['Crítico'] + conteo['Precaución']
porcentajeanomalias = (totalanomalias / totaldedatos) * 100
print(f"Porcentaje Anomalia es: {porcentajeanomalias}%")

#Calculando el promedios unicamente si hubo anomalias
 #(usando las listas creadas)
if totalanomalias > 0:
   promedio_presion = sum(presiones_anonalias) / len(presiones_anonalias)
   print(f"Promedio Presión en Riesgo: {promedio_presion}")
   promedio_temperaturas = sum(temperaturas_anomalias)/len(temperaturas_anomalias)
   print(f"Promedio Temperatura en Riesgo: {promedio_temperaturas}")

#Observandoo valores de diccionario
print(f"Diccionario de conteo final: {conteo}")

"""Para el siguiente análisis, se tomará en cuanta:
*   Indica el valor final de tu diccionario conteo.
*   Indica el porcentaje de anomalía.
*   Indica el promedio de Presión y Temperatura en condiciones de anomalía.
*   Análisis: Entre la temperatura y la presión, ¿Cuál es el factor que más influye para
que la bomba entre en un estado crítico?

Se observa en el diccionario y por el porcentaje de anomalias que hay 81 casos donde la bomba esta operando bajo un estres la mayor parte del tiempo, y 19 casos es estado normal, siento una alerta 11 en estado critico y 70 que hacen el llamado a precaución.

En resumen valor final del diccionario es (Crítico: 11, Precaución: 70, Normal: 19) para un 81% de anomalias.

El promedio de la presion fue de 2733 y la temperatura 136, de acuero a este resultado y a los parametros establecidos:
*   CRÍTICO: Presión > 3000 y Temperatura > 150.
*   PRECAUCIÓN: Presión > 2500 o Temperatura > 120
Entre la temperatura y la presión, ¿Cuál es el factor que más influye para que la bomba entre en un estado crítico?

Para entrar en estado Crítico, ambos parámetros deben superar sus límites >3000 psi y >150°C. Sin embargo basandome en datos y poco de experiencia me inclino por la temperatura, por qué? porque presenta datos reflejados donde la temperatura registro picos que superan su parámetro critico de 150 grados aún con presiones con numeros que indican precaución. Aunque el promedio de presión 2733.47 está numéricamente más cerca del límite crítico de 3000, la temperatura 136.76 presenta una brecha de seguridad mucho más estrecha frente a su límite crítico de 150 grados. En campo, las bombas de inyección tienen válvulas que regulan su presión, es decir, para que baje o suba su presion en este caso para que suba 267 psi repentidamente no es algo que suceda tan drásticamente.

Cabe destacar que los parámetros del ejercicio se centran en la "sobrepresión". Sin embargo, en el campo, los valores bajos de presión registrados (cercanos a 1800 psi) suelen ser indicadores de cavitación, un fenómeno que también pone en riesgo la integridad de la bomba pero que, bajo la lógica actual del algoritmo, se clasifica como estado "Normal".
"""